import type { Destination } from "./types";

type Seed = Omit<Destination, "crowdScore" | "currentVisitors" | "slug" | "region" | "state" | "imageUrl"> & {
  region?: string;
};

const g = (a: string, b: string) => `linear-gradient(135deg, ${a} 0%, ${b} 100%)`;

const RAW: (Seed & { gradient: string })[] = [
  {
    id: "chitrakote-falls",
    name: "Chitrakote Falls",
    description:
      "India's widest waterfall — the Indravati river plunges ~30 m across a horseshoe-shaped cliff nearly 300 m wide. Spectacular in and just after the monsoon, and the region's biggest crowd magnet.",
    latitude: 19.2064,
    longitude: 81.6997,
    category: "waterfall",
    tags: ["waterfalls", "nature", "photography", "adventure"],
    capacity: 1500,
    baseVisitors: 1290,
    environmentalSensitivity: 82,
    ecoScore: 74,
    popularityScore: 96,
    localEconomyScore: 62,
    averageVisitMinutes: 120,
    bestStartHour: 7,
    bestEndHour: 10,
    averageCost: 150,
    localOpportunities: ["Boating", "Local guides", "Food stalls"],
    gradient: g("#0F4C5C", "#5BA7D1"),
  },
  {
    id: "tirathgarh-falls",
    name: "Tirathgarh Falls",
    description:
      "A tiered 90 m cascade inside Kanger Valley National Park where the Mugabahar stream steps down a series of rock terraces. Very popular on weekends.",
    latitude: 18.8997,
    longitude: 81.9531,
    category: "waterfall",
    tags: ["waterfalls", "nature", "photography"],
    capacity: 1200,
    baseVisitors: 880,
    environmentalSensitivity: 78,
    ecoScore: 76,
    popularityScore: 88,
    localEconomyScore: 58,
    averageVisitMinutes: 100,
    bestStartHour: 8,
    bestEndHour: 11,
    averageCost: 120,
    localOpportunities: ["Local guides", "Tribal snacks", "Forest trekking"],
    gradient: g("#12372A", "#3C9A71"),
  },
  {
    id: "tamra-ghoomar",
    name: "Tamra Ghoomar Waterfall",
    description:
      "A tall, slender monsoon waterfall ringed by sal forest, a short drive from Chitrakote. Quiet trails, excellent photography light, and village-run refreshment points.",
    latitude: 19.1658,
    longitude: 81.7946,
    category: "waterfall",
    tags: ["waterfalls", "nature", "photography", "rural"],
    capacity: 650,
    baseVisitors: 200,
    environmentalSensitivity: 58,
    ecoScore: 86,
    popularityScore: 44,
    localEconomyScore: 84,
    averageVisitMinutes: 90,
    bestStartHour: 7,
    bestEndHour: 11,
    averageCost: 60,
    localOpportunities: ["Rural homestays", "Local guides", "Handicrafts", "Local food", "Community tourism"],
    gradient: g("#1B5E4A", "#A7D7C5"),
  },
  {
    id: "mendri-ghoomar",
    name: "Mendri Ghoomar Falls",
    description:
      "A dramatic valley-edge waterfall with a panoramic viewpoint over dense forest. Lightly visited and managed with a local eco-development committee.",
    latitude: 19.1952,
    longitude: 81.7512,
    category: "waterfall",
    tags: ["waterfalls", "nature", "photography", "adventure"],
    capacity: 500,
    baseVisitors: 140,
    environmentalSensitivity: 60,
    ecoScore: 84,
    popularityScore: 38,
    localEconomyScore: 79,
    averageVisitMinutes: 75,
    bestStartHour: 8,
    bestEndHour: 12,
    averageCost: 50,
    localOpportunities: ["Local guides", "Village tea stalls", "Community tourism"],
    gradient: g("#264653", "#2A9D8F"),
  },
  {
    id: "chitradhara-falls",
    name: "Chitradhara Falls",
    description:
      "A gentle, wide cascade near Potanar village, surrounded by paddy fields. Perfect for relaxed family visits and rural walks.",
    latitude: 19.1205,
    longitude: 82.0741,
    category: "waterfall",
    tags: ["waterfalls", "nature", "rural", "photography"],
    capacity: 500,
    baseVisitors: 105,
    environmentalSensitivity: 50,
    ecoScore: 82,
    popularityScore: 35,
    localEconomyScore: 76,
    averageVisitMinutes: 60,
    bestStartHour: 9,
    bestEndHour: 16,
    averageCost: 40,
    localOpportunities: ["Rural homestays", "Local food", "Paddy-field walks"],
    gradient: g("#2E7D5B", "#E9C46A"),
  },
  {
    id: "kanger-valley",
    name: "Kanger Valley National Park",
    description:
      "200 km² of moist deciduous forest, limestone karst and the Kanger river. Home to the Bastar hill myna, leopards and flying squirrels.",
    latitude: 18.8547,
    longitude: 81.9811,
    category: "wildlife",
    tags: ["wildlife", "nature", "adventure", "photography"],
    capacity: 2000,
    baseVisitors: 1100,
    environmentalSensitivity: 90,
    ecoScore: 88,
    popularityScore: 78,
    localEconomyScore: 66,
    averageVisitMinutes: 180,
    bestStartHour: 6,
    bestEndHour: 10,
    averageCost: 350,
    localOpportunities: ["Naturalist guides", "Jeep safaris", "Forest rest houses"],
    gradient: g("#0B2A1F", "#2E7D5B"),
  },
  {
    id: "kutumsar-caves",
    name: "Kutumsar Caves",
    description:
      "A 330 m limestone cave system with stalactites, stalagmites and endemic blind fish. Narrow passages mean capacity is strictly limited.",
    latitude: 18.8716,
    longitude: 81.9362,
    category: "caves",
    tags: ["adventure", "heritage", "nature", "photography"],
    capacity: 400,
    baseVisitors: 272,
    environmentalSensitivity: 94,
    ecoScore: 70,
    popularityScore: 80,
    localEconomyScore: 55,
    averageVisitMinutes: 75,
    bestStartHour: 9,
    bestEndHour: 12,
    averageCost: 200,
    localOpportunities: ["Cave guides", "Torch rental"],
    gradient: g("#3D2C2E", "#8D6E63"),
  },
  {
    id: "kailash-gufa",
    name: "Kailash Gufa",
    description:
      "A lesser-known cave on a forested hillock within Kanger Valley, with a naturally formed Shiva-linga formation and a quiet trek to the entrance.",
    latitude: 18.8305,
    longitude: 82.0203,
    category: "caves",
    tags: ["adventure", "heritage", "nature"],
    capacity: 300,
    baseVisitors: 66,
    environmentalSensitivity: 72,
    ecoScore: 80,
    popularityScore: 30,
    localEconomyScore: 70,
    averageVisitMinutes: 70,
    bestStartHour: 8,
    bestEndHour: 12,
    averageCost: 120,
    localOpportunities: ["Local guides", "Trekking porters"],
    gradient: g("#4E342E", "#A1887F"),
  },
  {
    id: "danteshwari-temple",
    name: "Danteshwari Temple, Dantewada",
    description:
      "A revered 14th-century Shakti Peeth at the confluence of the Shankini and Dankini rivers — the spiritual heart of the Bastar Dussehra.",
    latitude: 18.8981,
    longitude: 81.3483,
    category: "heritage",
    tags: ["culture", "heritage", "photography"],
    capacity: 3000,
    baseVisitors: 2130,
    environmentalSensitivity: 45,
    ecoScore: 62,
    popularityScore: 86,
    localEconomyScore: 60,
    averageVisitMinutes: 90,
    bestStartHour: 6,
    bestEndHour: 9,
    averageCost: 0,
    localOpportunities: ["Prasad stalls", "Local guides"],
    gradient: g("#7B2D26", "#E07832"),
  },
  {
    id: "barsur-temples",
    name: "Barsur Temple Town",
    description:
      "An 11th-century Nagvanshi capital with the Mama-Bhanja temple, twin Ganesh idols and Chandraditya temple — a peaceful, under-visited heritage circuit.",
    latitude: 19.1336,
    longitude: 81.3867,
    category: "heritage",
    tags: ["heritage", "culture", "photography", "rural"],
    capacity: 800,
    baseVisitors: 145,
    environmentalSensitivity: 55,
    ecoScore: 80,
    popularityScore: 34,
    localEconomyScore: 82,
    averageVisitMinutes: 90,
    bestStartHour: 8,
    bestEndHour: 17,
    averageCost: 30,
    localOpportunities: ["Heritage walks", "Local guides", "Handicrafts", "Village cuisine"],
    gradient: g("#6D4C41", "#E0A72F"),
  },
  {
    id: "saat-dhara",
    name: "Saat Dhara Falls",
    description:
      "The Indravati splits into seven streams near Barsur, forming a chain of cascades through rocky forest — a quiet alternative to the headline falls.",
    latitude: 19.1419,
    longitude: 81.3322,
    category: "waterfall",
    tags: ["waterfalls", "nature", "photography", "adventure"],
    capacity: 450,
    baseVisitors: 85,
    environmentalSensitivity: 62,
    ecoScore: 85,
    popularityScore: 28,
    localEconomyScore: 74,
    averageVisitMinutes: 80,
    bestStartHour: 8,
    bestEndHour: 15,
    averageCost: 40,
    localOpportunities: ["Local guides", "River picnics", "Community tourism"],
    gradient: g("#1D3557", "#5BA7D1"),
  },
  {
    id: "bastar-palace",
    name: "Bastar Palace, Jagdalpur",
    description:
      "The royal seat of the Kakatiya rulers of Bastar, central to the 75-day Bastar Dussehra festival. Architecture blends colonial and tribal motifs.",
    latitude: 19.0797,
    longitude: 82.0253,
    category: "heritage",
    tags: ["heritage", "culture", "photography"],
    capacity: 1000,
    baseVisitors: 480,
    environmentalSensitivity: 35,
    ecoScore: 66,
    popularityScore: 64,
    localEconomyScore: 58,
    averageVisitMinutes: 60,
    bestStartHour: 10,
    bestEndHour: 17,
    averageCost: 50,
    localOpportunities: ["Heritage guides", "Dussehra crafts"],
    gradient: g("#5D4037", "#D7A86E"),
  },
  {
    id: "dalpat-sagar",
    name: "Dalpat Sagar Lake",
    description:
      "A 400-year-old man-made lake in Jagdalpur with an island shrine, boating and sunset promenades — an easy evening stop.",
    latitude: 19.0869,
    longitude: 82.0161,
    category: "lake",
    tags: ["nature", "photography", "food"],
    capacity: 1500,
    baseVisitors: 660,
    environmentalSensitivity: 48,
    ecoScore: 68,
    popularityScore: 60,
    localEconomyScore: 64,
    averageVisitMinutes: 60,
    bestStartHour: 16,
    bestEndHour: 19,
    averageCost: 60,
    localOpportunities: ["Boating", "Street food", "Local vendors"],
    gradient: g("#023E8A", "#90E0EF"),
  },
  {
    id: "anthropological-museum",
    name: "Anthropological Museum, Jagdalpur",
    description:
      "Tribal artefacts, dhokra metalwork, musical instruments and dress from the Gond, Muria, Maria and Halba communities of Bastar.",
    latitude: 19.0668,
    longitude: 82.0326,
    category: "culture",
    tags: ["culture", "heritage"],
    capacity: 500,
    baseVisitors: 130,
    environmentalSensitivity: 20,
    ecoScore: 72,
    popularityScore: 40,
    localEconomyScore: 60,
    averageVisitMinutes: 60,
    bestStartHour: 10,
    bestEndHour: 17,
    averageCost: 20,
    localOpportunities: ["Tribal art shop", "Local guides"],
    gradient: g("#4A148C", "#CE93D8"),
  },
  {
    id: "kondagaon-shilpgram",
    name: "Kondagaon Shilpgram",
    description:
      "A living crafts village famous for Bastar dhokra bell-metal, wrought iron and terracotta. Watch artisans at work and buy directly from them.",
    latitude: 19.5946,
    longitude: 81.6647,
    category: "rural",
    tags: ["culture", "rural", "food", "heritage"],
    capacity: 600,
    baseVisitors: 95,
    environmentalSensitivity: 30,
    ecoScore: 90,
    popularityScore: 32,
    localEconomyScore: 95,
    averageVisitMinutes: 120,
    bestStartHour: 9,
    bestEndHour: 17,
    averageCost: 80,
    localOpportunities: ["Artisan workshops", "Handicrafts", "Rural homestays", "Local food", "Community tourism"],
    gradient: g("#8D5524", "#E0A72F"),
  },
  {
    id: "tokapal-haat",
    name: "Tokapal Tribal Haat",
    description:
      "A weekly tribal market where Muria and Dhurwa communities trade forest produce, handicrafts and traditional food like chapda chutney and salphi.",
    latitude: 19.0292,
    longitude: 81.8603,
    category: "rural",
    tags: ["culture", "food", "rural", "photography"],
    capacity: 900,
    baseVisitors: 250,
    environmentalSensitivity: 28,
    ecoScore: 86,
    popularityScore: 42,
    localEconomyScore: 92,
    averageVisitMinutes: 90,
    bestStartHour: 9,
    bestEndHour: 14,
    averageCost: 50,
    localOpportunities: ["Local food", "Handicrafts", "Forest produce", "Community tourism"],
    gradient: g("#BC6C25", "#DDA15E"),
  },
];

export const HUBS: Record<string, { name: string; lat: number; lon: number }> = {
  jagdalpur: { name: "Jagdalpur", lat: 19.0748, lon: 82.008 },
};

export function crowdFromVisitors(visitors: number, capacity: number) {
  return Math.max(0, Math.min(100, Math.round((visitors / capacity) * 100)));
}

export const SEED_DESTINATIONS: Destination[] = RAW.map(({ gradient, region, ...d }) => ({
  ...d,
  slug: d.id,
  region: region ?? "Bastar",
  state: "Chhattisgarh",
  imageUrl: gradient,
  currentVisitors: d.baseVisitors,
  crowdScore: crowdFromVisitors(d.baseVisitors, d.capacity),
}));
